### ISSUE TITLE
Promisify

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/null-check#1]
Is this something you would like to have promisified? Or is this a ponyfill?

**Comment by sindresorhus** [comment]
I originally followed the method used in core, but it's pretty awkward, so in hinsight I probably shouldn't have. This should rather be turned into a sync-only function and instead add process.nextTick here: https://github.com/sindresorhus/fs-access/blob/b03b3c23baa8869e6d3004461c3076412dc9ccb3/index.js#L17

**Comment by SamVerschueren** [comment]
So we should refactor this to only have one argument (no callback whatsoever)?

**Comment by sindresorhus** [comment]
Yes
